#!/usr/bin/env ruby
require 'optparse'
require 'vinz/clortho'

begin
  ssh_setup = Vinz::Clortho::SSHSetup.new
  initials = ARGV[0]
  sshlogin_cli = Vinz::Clortho::Cli::SSHLogin.new

  parser = OptionParser.new do |opts|
    opts.banner = ssh_setup.usage_msg

    opts.on('-h', '--help', 'Shows help') do |v|
      puts parser
      exit 0
    end
    opts.on('-v', '--version', 'Returns version') do |v|
      puts Vinz::Clortho::VERSION
      exit 0
    end
    opts.on('--add-to-github', 'Adds a public key to Github') do |v|
      sshlogin_cli.add_to_github(initials)
      exit 0
    end
  end

  parser.parse!
  sshlogin_cli.perform(initials)

rescue OptionParser::InvalidOption => e
  puts parser
  exit 1
rescue => e
  puts e.message
  puts parser
  exit (e.is_a? Vinz::Clortho::UserNotFoundError) ? 2 : 1
end

